### ISSUE TITLE
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

### ISSUE THREAD

**Issue by kasagon** [cglatot/PokeManager#21]
I just installed this application locally with Python 2.7.12 and tried to run this.
After running I immediately got this error:

```
C:\PokeManager>python ".\pogo\demo.py" -a google -u "myemail@gmail.com" -p "mypassword" -l "xx.lat , xx.long"
Traceback (most recent call last):
  File ".\pogo\demo.py", line 14, in <module>
    from api import PokeAuthSession
  File "C:\PokeManager\pogo\api.py", line 10, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 44, in <module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\__init__.py", line 78, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 46, in <module>
    """
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'
```

Some information about my software:

> Python 2.7.12
> pip 8.1.2
> git version 2.9.2.windows.1
> java version 1.8.0_102-b14 64-bit
> Windows 10 pro 64-bit

**Comment by cglatot** [comment]
Have you followed the Readme instructions?

Installed the requirements.txt?

Are you using 2 Factor Authorisation?

Have you tried updating python and pip?

Tried updating the requirements.txt (using --upgrade for pip)?

**Comment by kasagon** [comment]
@cglatot 
I followed the Readme instructions.txt
I installed the requirements
I am using 2 Faction Authorisation
I fresh installed Python and pip this morning
Tried to update the requirements.txt as well

I don't know if something has to do with it, but according to other github projects and Reddit it is possible that they are busy patching the API's at this moment.

**Comment by cglatot** [comment]
Did you follow what I said on the Readme about 2FA?

**Comment by kasagon** [comment]
@cglatot About the App Password?
I haven't seen that, so I did not follow that.

But, when I follow that link, I get this error (translated) on the Google site: 

> The setting you are searching, is not available for your account

**Comment by cglatot** [comment]
https://support.google.com/accounts/answer/185833
